config/routes.rb
Rails.application.routes.draw do
  resources :automations

  resources :macros

  resources :triggers

  resources :packages

  root 'packages#index'

  match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/macro.rb
class Macro < ActiveRecord::Base

belongs_to :package
end

app/controllers/macros_controller.rb
class MacrosController < ApplicationController
  before_action :set_macro, only: [:show, :edit, :update, :destroy, :sync]
  before_action :confirm_logged_in, only: :sync


  # GET /macros
  # GET /macros.json
  def index
    @macros = Macro.all
  end

  # GET /macros/1
  # GET /macros/1.json
  def show
  end

  # GET /macros/new
  def new
    @macro = Macro.new
  end

  # GET /macros/1/edit
  def edit
  end

  # POST /macros
  # POST /macros.json
  def create
    @macro = Macro.new(macro_params)

    respond_to do |format|
      if @macro.save
        format.html { redirect_to @macro, notice: 'Macro was successfully created.' }
        format.json { render :show, status: :created, location: @macro }
      else
        format.html { render :new }
        format.json { render json: @macro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /macros/1
  # PATCH/PUT /macros/1.json
  def update
    respond_to do |format|
      if @macro.update(macro_params)
        format.html { redirect_to @macro, notice: 'Macro was successfully updated.' }
        format.json { render :show, status: :ok, location: @macro }
      else
        format.html { render :edit }
        format.json { render json: @macro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /macros/1
  # DELETE /macros/1.json
  def destroy
    @macro.destroy
    respond_to do |format|
      format.html { redirect_to macros_url, notice: 'Macro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /macros/1/sync
  def sync
    jsonData = @macro.json
    client.macros.create(jsonData)
    flash[:notice] = "Macro Created Successfully!"
    redirect_to (:back)
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_macro
    @macro = Macro.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def macro_params
    params.require(:macro).permit(:name, :tags, :description, :json, :package_id)
  end
end

app/helpers/macros_helper.rb
module MacrosHelper
end

app/views/macros/_form.html.erb
<%= form_for(@macro) do |f| %>
  <% if @macro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@macro.errors.count, "error") %> prohibited this macro from being saved:</h2>

      <ul>
      <% @macro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tags %><br>
    <%= f.text_field :tags %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :json %><br>
    <%= f.text_field :json %>
  </div>
  <div class="field">
    <%= f.label :package_id %><br>
    <%= f.number_field :package_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/macros/edit.html.erb
<h1>Editing Macro</h1>

<%= render 'form' %>

<%= link_to 'Show', @macro %> |
<%= link_to 'Back', macros_path %>

app/views/macros/index.html.erb
<h1>Macros</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Tags</th>
      <th>Description</th>
      <!-- <th>Json</th> -->
      <!-- <th>Package</th> -->
      <th>Add to account</th>
      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @macros.each do |macro| %>
      <tr>
        <td><%= macro.name %></td>
        <td><%= macro.tags %></td>
        <td><%= macro.description %></td>
        <!-- <td><%= macro.json %></td> -->
        <!-- <td><%= macro.package_id %></td> -->
        <td><%= link_to 'Add', :action => 'sync', :id => macro.id %></td>
        <!-- <td><%= link_to 'Edit', edit_macro_path(macro) %></td> -->
        <!-- <td><%= link_to 'Destroy', macro, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!-- <%= link_to 'New Macro', new_macro_path %> -->

app/views/macros/new.html.erb
<h1>New Macro</h1>

<%= render 'form' %>

<%= link_to 'Back', macros_path %>

app/views/macros/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @macro.name %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @macro.tags %>
</p>

<p>
  <strong>Description:</strong>
  <%= @macro.description %>
</p>

<p>
  <strong>Json:</strong>
  <%= @macro.json %>
</p>

<p>
  <strong>Package:</strong>
  <%= @macro.package_id %>
</p>

<%= link_to 'Edit', edit_macro_path(@macro) %> |
<%= link_to 'Back', macros_path %>