config/routes.rb
Rails.application.routes.draw do
  resources :automations

  resources :macros

  resources :triggers

  resources :packages

  root 'packages#index'

  match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/automation.rb
class Automation < ActiveRecord::Base

belongs_to :package
end

app/controllers/automations_controller.rb
class AutomationsController < ApplicationController
  before_action :set_automation, only: [:show, :edit, :update, :destroy, :sync]
  before_action :confirm_logged_in, only: :sync


  # GET /automations
  # GET /automations.json
  def index
    @automations = Automation.all
  end

  # GET /automations/1
  # GET /automations/1.json
  def show
  end

  # GET /automations/new
  def new
    @automation = Automation.new
  end

  # GET /automations/1/edit
  def edit
  end

  # POST /automations
  # POST /automations.json
  def create
    @automation = Automation.new(automation_params)

    respond_to do |format|
      if @automation.save
        format.html { redirect_to @automation, notice: 'Automation was successfully created.' }
        format.json { render :show, status: :created, location: @automation }
      else
        format.html { render :new }
        format.json { render json: @automation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /automations/1
  # PATCH/PUT /automations/1.json
  def update
    respond_to do |format|
      if @automation.update(automation_params)
        format.html { redirect_to @automation, notice: 'Automation was successfully updated.' }
        format.json { render :show, status: :ok, location: @automation }
      else
        format.html { render :edit }
        format.json { render json: @automation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /automations/1
  # DELETE /automations/1.json
  def destroy
    @automation.destroy
    respond_to do |format|
      format.html { redirect_to automations_url, notice: 'Automation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /automations/1/sync
  def sync
    jsonData = @automation.json
    client.automations.create(jsonData)
    flash[:notice] = "Automation Created Successfully!"
    redirect_to (:back)
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_automation
    @automation = Automation.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def automation_params
    params.require(:automation).permit(:name, :tags, :description, :json, :package_id)
  end
end

app/helpers/automations_helper.rb
module AutomationsHelper
end

app/views/automations/_form.html.erb
<%= form_for(@automation) do |f| %>
  <% if @automation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@automation.errors.count, "error") %> prohibited this automation from being saved:</h2>

      <ul>
      <% @automation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tags %><br>
    <%= f.text_field :tags %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :json %><br>
    <%= f.text_field :json %>
  </div>
  <div class="field">
    <%= f.label :package_id %><br>
    <%= f.number_field :package_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/automations/edit.html.erb
<h1>Editing Automation</h1>

<%= render 'form' %>

<%= link_to 'Show', @automation %> |
<%= link_to 'Back', automations_path %>

app/views/automations/index.html.erb
<h1>Automations</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Tags</th>
      <th>Description</th>
      <!-- <th>Json</th> -->
      <!-- <th>Package</th> -->
      <th>Add to account</th>

    </tr>
  </thead>

  <tbody>
    <% @automations.each do |automation| %>
      <tr>
        <td><%= automation.name %></td>
        <td><%= automation.tags %></td>
        <td><%= automation.description %></td>
        <!-- <td><%= automation.json %></td> -->
        <!-- <td><%= automation.package_id %></td> -->
        <td><%= link_to 'Add', :action => 'sync', :id => automation.id %></td>
        <!-- <td><%= link_to 'Edit', edit_automation_path(automation) %></td> -->
        <!-- <td><%= link_to 'Destroy', automation, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!-- <%= link_to 'New Automation', new_automation_path %> -->

app/views/automations/new.html.erb
<h1>New Automation</h1>

<%= render 'form' %>

<%= link_to 'Back', automations_path %>

app/views/automations/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @automation.name %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @automation.tags %>
</p>

<p>
  <strong>Description:</strong>
  <%= @automation.description %>
</p>

<p>
  <strong>Json:</strong>
  <%= @automation.json %>
</p>

<p>
  <strong>Package:</strong>
  <%= @automation.package_id %>
</p>

<%= link_to 'Edit', edit_automation_path(@automation) %> |
<%= link_to 'Back', automations_path %>