config/routes.rb
Rails.application.routes.draw do
  resources :automations

  resources :macros

  resources :triggers

  resources :packages

  root 'packages#index'

  match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/trigger.rb
class Trigger < ActiveRecord::Base

  validates :name, presence: true
  validates :tags, presence: true
  validates :json, presence: true

  belongs_to :package
end

app/controllers/triggers_controller.rb
class TriggersController < ApplicationController
  before_action :set_trigger, only: [:show, :edit, :update, :destroy, :sync]
  before_action :confirm_logged_in, only: :sync

  # GET /triggers
  # GET /triggers.json
  def index
    @triggers = Trigger.all
  end

  # GET /triggers/1
  # GET /triggers/1.json
  def show
  end

  # GET /triggers/new
  def new
    @trigger = Trigger.new
  end

  # GET /triggers/1/edit
  def edit
  end

  # POST /triggers
  # POST /triggers.json
  def create
    @trigger = Trigger.new(trigger_params)

    respond_to do |format|
      if @trigger.save
        format.html { redirect_to @trigger, notice: 'Trigger was successfully created.' }
        format.json { render :show, status: :created, location: @trigger }
      else
        format.html { render :new }
        format.json { render json: @trigger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /triggers/1
  # PATCH/PUT /triggers/1.json
  def update
    respond_to do |format|
      if @trigger.update(trigger_params)
        format.html { redirect_to @trigger, notice: 'Trigger was successfully updated.' }
        format.json { render :show, status: :ok, location: @trigger }
      else
        format.html { render :edit }
        format.json { render json: @trigger.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /triggers/1
  # DELETE /triggers/1.json
  def destroy
    @trigger.destroy
    respond_to do |format|
      format.html { redirect_to triggers_url, notice: 'Trigger was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /triggers/1/sync
  def sync
    jsonData = @trigger.json
    client.triggers.create(jsonData)
    flash[:notice] = "Trigger Created Successfully!"
    redirect_to (:back)
  end
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_trigger
    @trigger = Trigger.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def trigger_params
    params.require(:trigger).permit(:name, :tags, :description, :json, :package_id)
  end
end

app/helpers/triggers_helper.rb
module TriggersHelper
end

app/views/triggers/_form.html.erb
<%= form_for(@trigger) do |f| %>
  <% if @trigger.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trigger.errors.count, "error") %> prohibited this trigger from being saved:</h2>

      <ul>
      <% @trigger.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tags %><br>
    <%= f.text_field :tags %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :json %><br>
    <%= f.text_field :json %>
  </div>
  <div class="field">
    <%= f.label :package_id %><br>
    <%= f.number_field :package_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/triggers/edit.html.erb
<h1>Editing Trigger</h1>

<%= render 'form' %>

<%= link_to 'Show', @trigger %> |
<%= link_to 'Back', triggers_path %>

app/views/triggers/index.html.erb
<h1>Triggers</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Tags</th>
      <th>Description</th>
      <!-- <th>Package</th> -->
      <th>Add to account</th>
      <!-- <th>Json</th> -->
      <th></th>
    </tr>
  </thead>
<!-- <form> -->
  <tbody>
    <% @triggers.each do |trigger| %>
      <tr>
        <td><%= trigger.name %></td>
        <td><%= trigger.tags %></td>
        <td><%= trigger.description %></td>
        <!-- <td><%= trigger.json %></td> -->
        <!-- <td><%= trigger.package_id %></td> -->
        <td><%= link_to 'Add', :action => 'sync', :id => trigger.id %></td>
        <!-- <td><%= link_to 'Edit', edit_trigger_path(trigger) %></td> -->
        <!-- <td><%= link_to 'Destroy', trigger, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trigger', new_trigger_path, class: 'new_resource' %>

app/views/triggers/new.html.erb
<h1>New Trigger</h1>

<%= render 'form' %>

<%= link_to 'Back', triggers_path %>

app/views/triggers/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @trigger.name %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @trigger.tags %>
</p>

<p>
  <strong>Description:</strong>
  <%= @trigger.description %>
</p>

<!-- <p>
  <strong>Json:</strong>
  <%= @trigger.json %>
</p> -->

<p>
  <strong>Package:</strong>
  <%= @trigger.package_id %>
</p>

<%= link_to 'Edit', edit_trigger_path(@trigger) %> |
<%= link_to 'Back', triggers_path %>